TARGET = partitionTest

$(TARGET) : test.o functions.o 
	gcc test.o functions.o -o $(TARGET) 

test.o : test.c
	gcc -c test.c -o test.o

functions.o: functions.c
	gcc -c functions.c -o functions.o